outletobuv_core/outletobuv_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import IndexView

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

outletobuv_core/products/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static

from .views import about, products, index, product, parse_tsgoods_view, search_by_name, update_product_image,\
    ProductsListView, ProductDetailView, ProductUpdateView


app_name = 'products'

urlpatterns = [
        
    # path('', index, name='index'),
    # path('category/<int:category_id>/', products, name='category'),
    # path('page/<int:page_number>/', products, name='paginator'),
    # path('detail/<int:product_id>/', product, name='detail'),

    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:pk>/', ProductsListView.as_view(), name='category'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('product/<int:pk>/update_image/', ProductUpdateView.as_view(), name='update_product_image'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    
    path('search/', search_by_name, name='search'),
    path('about/', about, name='about'),
    path('update_image/<int:product_id>/', update_product_image, name='update_image'),
    path('parse-tsgoods/', parse_tsgoods_view, name='parse_tsgoods'),

    # path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    # path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
        

outletobuv_core/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .views import (UserLoginView, UserProfileView,
                    UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),

    # path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

outletobuv_core/products/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name ='Категория'
        verbose_name_plural = 'Категории'


class Color(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'


class Material(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'


class Size(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)    
    color = models.ManyToManyField(Color)
    material = models.ManyToManyField(Material)
    value = models.CharField(max_length=10)
    
    def __str__(self) -> str:
        color = ' '.join(str(color) for color in self.color.all())
        material = ' '.join(str(material) for material in self.material.all())
        return f'{self.value} | {self.product} | {color} | {material}'
    
    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'


class Product(models.Model):
    article = models.CharField(max_length=22)
    name = models.CharField(max_length=100)
    materials = models.ForeignKey(Material, on_delete=models.CASCADE)
    colors = models.ForeignKey(Color, on_delete=models.CASCADE)
    is_popular = models.BooleanField(default=False)
    season = models.CharField(max_length=200)
    price = models.CharField(max_length=20)
    image = models.ImageField(upload_to='imgs/products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    country = models.CharField(max_length=200)
    description = models.CharField(max_length=250, blank=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товар'
        ordering = ['article']

    def __str__(self) -> str:
        return f'{self.article}'
    

outletobuv_core/products/forms.py
from .models import Product
from django import forms


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['description', 'image']

outletobuv_core/products/views.py
from django.urls import reverse_lazy
from .forms import ProductImageForm
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Product, Size, Material, Color, Category
from django.core.paginator import Paginator
from .utils import test, handle_upload_avatar
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView


class IndexView(TemplateView):
    template_name = 'products/index.html'
    title = 'Outlet Obuv'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data()
        context['title'] = 'Store'


class ProductsListView(ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 15
    title = 'Outlet Obuv'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('pk')
        return queryset.filter(category_id=category_id) if category_id else queryset
    
    def get_context_data(self, *, object_list=None, **krwargs):
        context = super(ProductsListView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_id = self.kwargs.get('category_id')
        product_color = self.object.colors
        product_material = self.object.materials

        sizes_query = Size.objects.filter(
                                          material=product_material,
                                          color=product_color
                                          )
        try:
            unique_sizes = {size.value for size in sizes_query}
            sorted_unique_sizes = sorted(unique_sizes, key=int)
        except:
            sorted_unique_sizes = sizes_query

        context['material'] = product_material
        context['color'] = product_color
        context['sizes'] = sorted_unique_sizes

        return context


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductImageForm
    template_name = 'product/update_product.html'
    success_url = reverse_lazy('update_product_image')

    def form_valid(self, form):
        product = form.save(commit=False)
        product.image = self.request.FILES['image']
        product.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('products:detail', kwargs={'pk': self.object.pk})


def product(request, product_id):

    product = Product.objects.get(id=product_id)

    product_color = product.colors
    product_material = product.materials

    size_queryset = Size.objects.filter(
        color=product_color,
        material=product_material
    )
    try:
        unique_sizes = {size.value for size in size_queryset}
        sorted_unique_sizes = sorted(unique_sizes, key=int)
    except:
        sorted_unique_sizes = size_queryset

    context = {
        'product': product,
        'color': product_color,
        'sizes': sorted_unique_sizes
    }
    return render(request, 'products/product.html', context)


def update_product_image(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        product.image = request.FILES.get('image')
        product.save()
        return redirect('product_detail', product_id=product.id)

    return redirect('product_detail', product_id=product.id)


def parse_tsgoods_view(request):

    file_path = 'C:/Users/2021/Desktop/site/TSGoods.trs'

    try:
        test(file_path)
        return HttpResponse("File parsed successfully.")
    except Exception as e:
        print(e)
        return HttpResponse(f"Error occurred: {e}")


def index(request):
    context = {
        'products': Product.objects.all(),
        'title': 'Store',
        'is_promotion': 'True',
    }
    return render(request, 'products/index.html', context)


def search_by_name(request):
    query_data = request.GET.get('search_holder')
    query_article = Product.objects.filter(article__icontains=query_data)
    query_name = Product.objects.filter(name__icontains=query_data)
    query_size = Product.objects.filter(size__value__icontains=query_data)
    queryset = query_article | query_name | query_size
    categories = Category.objects.all()

    context = {
        'products': queryset,
        'categories': categories
    }
    
    return render(request, 'products/search.html', context)


def about(request):
    return render(request, 'about.html')


def products(request, category_id=None, page_number=1):
    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()
    
    per_page = 15
    paginator = Paginator(products, per_page)
    products_paginator = paginator.page(page_number)
    categories = Category.objects.all()
    context = {
        'title': 'Outlet Obuv',
        'categories': categories,
        'products': products_paginator,
    }
    return render(request, 'products/products.html', context)

outletobuv_core/products/templates/products/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Outlet obuv</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'products:index' %}">Outlet Obuv</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% comment %} <a class="nav-link active" aria-current="page" href="{% url 'products:paginator' %}">Каталог</a> {% endcomment %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:about' %}">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Пользователь
          </a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <form method="POST" action="{% url 'users:logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="dropdown-item">Выйти</button>
                </form>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="dropdown-item" href="{% url 'users:login' %}">Войти</a>
              </li>
              <li class="nav-item">
                <a class="dropdown-item" href="{% url 'users:registration' %}">Регистрация</a>
              </li>
            {% endif %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'products:search' %}">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name='search_holder'>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

  {% block content %} {% endblock %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

outletobuv_core/products/templates/products/baskets.html
{% if baskets %}

    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ basket.product.name }}</h5>
            <p class="card-text">{{ basket.product.description }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light">
                <div class="row text-center">
                    <div class="col-lg-4">
                        <input name="basketID" type="number" class="form-control"
                            value="{{ basket.quantity }}" min="0">
                    </div>
                    <div class="col-lg-4">{{ basket.sum }}</div>
                    <div class="col-lg-4">
                        <a href="{% url 'products:basket_remove' basket.id %}">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    {% endfor %}
    
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum }}</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
        Оформить заказ
    </a>

{% else %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина пуста <span class="badge badge-secondary badge-pill">3</span>
    </h4>
{% endif %}

outletobuv_core/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}
<!-- Page Content -->
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Outlet Obuv</h1>
                <p>
                    Доставка по всему миру!
                    {% if is_promotion %}
                    {% endif %}
                </p>
                {% comment %} <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:paginator' %} ">
                        Начать покупки
                    </a>
                </button> {% endcomment %}
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:category' 1 %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

{% endblock %}

outletobuv_core/products/templates/products/product.html
{% extends 'products/base.html' %}

{% block content %}
{% load static %}
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <h3>Артикул: {{ product.article }}</h3>
                {% if product.description %}
                    <h3>Описание :  {{ product.description }}</h3>
                {% endif %}
                <h3>Сезон: {{ product.season }}</h3>
                <h3>
                    Категория: <a href="{% url 'products:category' product.category.id %}">
                    {{ product.category.title }}</a>
                </h3>                            
                <h3>Материал: {{ product.materials.name }}</h3>
                <h3>Цвет: {{ color.name }}</h3>
                <h3>Размер: 
                {% for size in sizes %}
                    {{ size }}
                {% endfor %}
                </h3>
                <h3>Цена: {{ product.price }} тг.</h3>
            </div>
            <div class="col-lg-4 col-md-6">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="img-fluid mb-2"/>
                {% else %}
                    <img src="{{ '/media/imgs/default.PNG'}}" class="img-fluid mb-2">
                {% endif %}
            </div>
            <div class="col-lg-4 col-md-6" align="center">
                {% if user.is_superuser %}
                Hello, {{ user }}
                <form action="{% url 'products:update_product_image' product.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="image">
                    <button type="submit">Загрузить новое изображение</button>
                </form>
                {% else %}
                Ты не superuser
                тут будет какая то инфа)
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

outletobuv_core/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}

<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="mt-5">Outlet Obuv</h1>
            <div class="list-group">
                {% for category in categories %}
                <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.title }}</a>
                {% endfor %}
            </div>

        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{% url 'products:detail' product.id %}">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="img-fluid mb-2"/>
                    {% else %}
                        <img src="{{ '/media/imgs/default.PNG'}}" class="img-fluid mb-2">
                    {% endif %}
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                            <p class="article">Артикул: {{ product.article }}</p>
                            {% if product.name %}
                                <a href="{% url 'products:detail' product.id %}">{{ product.name }}</a>
                            {% else %}
                                <a href="{% url 'products:detail' product.id %}">Добавьте Наименование</a>
                            {% endif %}
                            </h4>
                            <p>Material: {{ product.materials }}</p>
                            <h5> Цена: {{ product.price }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                        {% comment %} <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id %}">Отправить в корзину</a> {% endcomment %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if products.has_previous %} {% url 'products:paginator' products.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Предыдущая</a>
                    </li>
                    {% with current=products.number max_pages=products.paginator.num_pages %}
                        {% for page in products.paginator.page_range %}
                            {% if page >= current|add:'-3' and page <= current|add:'3' %}
                                <li class="page-item {% if page == current %} active {% endif %}">
                                    <a class="page-link" href="{% url 'products:paginator' page %}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    {% endwith %}
                    <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                        <a class="page-link" href="{% if products.has_next %} {% url 'products:paginator' products.next_page_number %} {% else %} # {% endif %}"
                        >Следующая</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Since 2019</p>
    </div>
</footer>
{% endblock %}

outletobuv_core/products/templates/products/search.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}

<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="mt-5">Outlet Obuv</h1>
                <div class="list-group">
                    {% for category in categories %}
                    <a  href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.title }}</a>
                    {% endfor %}
                </div>

        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="img-fluid mb-2"/>
                    {% else %}
                        <img src="{{ '/media/imgs/default.PNG'}}" class="img-fluid mb-2">
                    {% endif %}
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                            <p class="article">Артикул: {{ product.article }}</p>
                            {% if product.name %}
                                <a href="{% url 'products:detail' product.id %}">{{ product.name }}</a>
                            {% else %}
                                <a href="{% url 'products:detail' product.id %}">Добавьте Наименование</a>
                            {% endif %}
                            </h4>
                            <p>Material: {{ product.materials }}</p>
                            <h5> Цена: {{ product.price }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                        {% comment %} <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id %}">Отправить в корзину</a> {% endcomment %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if products.has_previous %} {% url 'products:paginator' products.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Предыдущая</a>
                    </li>
                    {% with current=products.number max_pages=products.paginator.num_pages %}
                        {% for page in products.paginator.page_range %}
                            {% if page >= current|add:'-3' and page <= current|add:'3' %}
                                <li class="page-item {% if page == current %} active {% endif %}">
                                    <a class="page-link" href="{% url 'products:paginator' page %}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    {% endwith %}
                    <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                        <a class="page-link" href="{% if products.has_next %}
                        {% url 'products:paginator' products.next_page_number %} {% else %} # {% endif %}"
                        >Следующая</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Since 2019</p>
    </div>
</footer>
{% endblock %}